quarkus.log.level=INFO
intervals-client/mp-rest/url=https://intervals.icu/api/v1
intervals-client/mp-rest/readTimeout=3000
intervals-client/mp-rest/connectTimeout=3000
intervals-client.username=${INTERVALS_CLIENT_USERNAME}
intervals-client.password=${INTERVALS_CLIENT_PASSWORD}
claude.auth.token=${CLAUDE_AUTH_TOKEN}